## ZFAST
default:
  # shader affects retroarch shaders
  shader: handheld/zfast-lcd
  # scanline affect fba2x
  scanline: true
snes:
  shader: handheld/zfast-lcd
nes:
  shader: handheld/zfast-lcd
n64:
  shader: handheld/zfast-lcd
gba:
  shader: handheld/zfast-lcd
gb:
  shader: handheld/zfast-lcd
gbc:
  shader: handheld/zfast-lcd
fds:
  shader: handheld/zfast-lcd
virtualboy:
  shader: handheld/zfast-lcd
# Sega
sg1000:
  shader: handheld/zfast-lcd
mastersystem:
  shader: handheld/zfast-lcd
megadrive:
  shader: handheld/zfast-lcd
gamegear:
  shader: handheld/zfast-lcd
sega32x:
  shader: handheld/zfast-lcd
segacd:
  shader: handheld/zfast-lcd
# Arcade
neogeo:
  shader: handheld/zfast-lcd
neogeocd:
  shader: handheld/zfast-lcd
mame:
  shader: handheld/zfast-lcd
fba:
  shader: handheld/zfast-lcd
naomi:
  shader: handheld/zfast-lcd
atomiswave:
  shader: handheld/zfast-lcd
#
ngp:
  shader: handheld/zfast-lcd
ngpc:
  shader: handheld/zfast-lcd
gw:
  shader: handheld/zfast-lcd
vectrex:
  shader: handheld/zfast-lcd
lynx:
  shader: handheld/zfast-lcd
lutro:
  shader: handheld/zfast-lcd
wswan:
  shader: handheld/zfast-lcd
wswanc:
  shader: handheld/zfast-lcd
pcengine:
  shader: handheld/zfast-lcd
pcenginecd:
  shader: handheld/zfast-lcd
supergrafx:
  shader: handheld/zfast-lcd
atari800:
  shader: handheld/zfast-lcd
atari2600:
  shader: handheld/zfast-lcd
atari5200:
  shader: handheld/zfast-lcd
atari7800:
  shader: handheld/zfast-lcd
prboom:
  shader: handheld/zfast-lcd
psx:
  shader: handheld/zfast-lcd
colecovision:
  shader: handheld/zfast-lcd
# Computers
msx:
  shader: handheld/zfast-lcd
msx1:
  shader: handheld/zfast-lcd
msx2:
  shader: handheld/zfast-lcd
amiga:
  shader: handheld/zfast-lcd
amstradcpc:
  shader: handheld/zfast-lcd
atarist:
  shader: handheld/zfast-lcd
zxspectrum:
  shader: handheld/zfast-lcd
odyssey2:
  shader: handheld/zfast-lcd
zx81:
  shader: handheld/zfast-lcd
pcfx:
  shader: handheld/zfast-lcd
x68000:
  shader: handheld/zfast-lcd
