## RETRO
default:
  # shader affects retroarch shaders
  shader: handheld/bevel
  # scanline affect fba2x
  scanline: false
snes:
  shader: handheld/bevel
nes:
  shader: handheld/bevel
n64:
  shader: handheld/bevel
gba:
  shader: handheld/bevel
gb:
  shader: handheld/bevel
gbc:
  shader: handheld/bevel
fds:
  shader: handheld/bevel
virtualboy:
  shader: handheld/bevel
# Sega
sg1000:
  shader: handheld/bevel
mastersystem:
  shader: handheld/bevel
megadrive:
  shader: handheld/bevel
gamegear:
  shader: handheld/bevel
sega32x:
  shader: handheld/bevel
segacd:
  shader: handheld/bevel
# Arcade
neogeo:
  shader: handheld/bevel
neogeocd:
  shader: handheld/bevel
mame:
  shader: handheld/bevel
fba:
  shader: handheld/bevel
naomi:
  shader: handheld/bevel
atomiswave:
  shader: handheld/bevel
#
ngp:
  shader: handheld/bevel
ngpc:
  shader: handheld/bevel
gw:
  shader: handheld/bevel
vectrex:
  shader: handheld/bevel
lynx:
  shader: handheld/bevel
lutro:
  shader: handheld/bevel
wswan:
  shader: handheld/bevel
wswanc:
  shader: handheld/bevel
pcengine:
  shader: handheld/bevel
pcenginecd:
  shader: handheld/bevel
supergrafx:
  shader: handheld/bevel
atari800:
  shader: handheld/bevel
atari2600:
  shader: handheld/bevel
atari5200:
  shader: handheld/bevel
atari7800:
  shader: handheld/bevel
prboom:
  shader: handheld/bevel
psx:
  shader: handheld/bevel
colecovision:
  shader: handheld/bevel
# Computers
msx:
  shader: handheld/bevel
msx1:
  shader: handheld/bevel
msx2:
  shader: handheld/bevel
amiga:
  shader: handheld/bevel
amstradcpc:
  shader: handheld/bevel
atarist:
  shader: handheld/bevel
zxspectrum:
  shader: handheld/bevel
odyssey2:
  shader: handheld/bevel
zx81:
  shader: handheld/bevel
pcfx:
  shader: handheld/bevel
x68000:
  shader: handheld/bevel
